import Head from "next/head";
import CallToAction from "../../components/CallToAction";
import Creators from "../../components/Creators";
import Footer from "../../components/Footer/Footer";
// import React from "react";
// import Image from 'next/image'
import Header from "../../components/Header";
import Introducing from "../../components/Introducing";
import Manufacturers from "../../components/Manufacturers";
import Navbar from "../../components/Navbar";
import OurWhy from "../../components/OurWhy";
import Showcase from "../../components/Showcase";
import Users from "../../components/Users";
import Values from "../../components/Values";
// import styles from '../styles/Home.module.css'
// import data from "../../data";

export default function Home() {
  return (
    <div>
      <Head>
        <title>edekee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Header />
        <Values />
        <Showcase />
        <Introducing />
        <Users />
        <Manufacturers />
        <Creators />
        <CallToAction />
        <OurWhy />
        <Footer />
      </main>
    </div>
  );
}
